const_type! { OUT, u8,
	/// [`LOGFONT`](crate::LOGFONT) `lfOutPrecision`.

	DEFAULT_PRECIS, 0
	STRING_PRECIS, 1
	CHARACTER_PRECIS, 2
	STROKE_PRECIS, 3
	TT_PRECIS, 4
	DEVICE_PRECIS, 5
	RASTER_PRECIS, 6
	TT_ONLY_PRECIS, 7
	OUTLINE_PRECIS, 8
	SCREEN_OUTLINE_PRECIS, 9
	PS_ONLY_PRECIS, 10
}